/**
 * Client-side accessor for the build-time-derived per-language text-source
 * catalog (data/source-catalog.json, generated by scripts/fetch-data.mjs from
 * cdn.bibel.wiki/dbt/_app/catalog-overlap.json — see that script for the
 * derivation and the "id left out when ambiguous" caveat). Fetched once per
 * session and cached, same pattern as app-config.ts's loadNavBase().
 *
 * For Astro build-time/prerender code (not a browser context), import
 * data/source-catalog.json directly instead — see src/pages/[iso]/index.astro.
 */

export interface ResolvedSource {
  provider: "pkf" | "helloao" | "dbt"
  id?: string
}

export type SourceCatalog = Record<string, { nt?: ResolvedSource; ot?: ResolvedSource }>

let catalogPromise: Promise<SourceCatalog> | null = null

export function loadSourceCatalog(): Promise<SourceCatalog> {
  if (catalogPromise) return catalogPromise
  catalogPromise = fetch("/source-catalog.json")
    .then((r) => (r.ok ? (r.json() as Promise<SourceCatalog>) : {}))
    .catch(() => ({}))
  return catalogPromise
}

/** The build-time-resolved default provider (+ id, when unambiguous) for iso+canon. */
export async function resolveTextSource(iso: string, canon: "nt" | "ot"): Promise<ResolvedSource | null> {
  const catalog = await loadSourceCatalog()
  return catalog[iso]?.[canon] ?? null
}
